name: Build SACarCam

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Build ReleaseVC Win32
        run: msbuild SACarCam.sln /p:Configuration=ReleaseVC /p:Platform=x86 /p:PlatformToolset=v142

      - name: Upload SACarCam.asi
        uses: actions/upload-artifact@v4
        with:
          name: SACarCam
          path: SACarCam/ReleaseVC/SACarCam.asi
